// Autogenerated from Pigeon (v3.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.voodoostack.flutter_estimote;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class estimote_api {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class EstimoteBeacon {
    private @Nullable String uuid;
    public @Nullable String getUuid() { return uuid; }
    public void setUuid(@Nullable String setterArg) {
      this.uuid = setterArg;
    }

    public static final class Builder {
      private @Nullable String uuid;
      public @NonNull Builder setUuid(@Nullable String setterArg) {
        this.uuid = setterArg;
        return this;
      }
      public @NonNull EstimoteBeacon build() {
        EstimoteBeacon pigeonReturn = new EstimoteBeacon();
        pigeonReturn.setUuid(uuid);
        return pigeonReturn;
      }
    }
    @NonNull Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("uuid", uuid);
      return toMapResult;
    }
    static @NonNull EstimoteBeacon fromMap(@NonNull Map<String, Object> map) {
      EstimoteBeacon pigeonResult = new EstimoteBeacon();
      Object uuid = map.get("uuid");
      pigeonResult.setUuid((String)uuid);
      return pigeonResult;
    }
  }
  private static class EstimoteAPICodec extends StandardMessageCodec {
    public static final EstimoteAPICodec INSTANCE = new EstimoteAPICodec();
    private EstimoteAPICodec() {}
    @Override
    protected Object readValueOfType(byte type, ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return EstimoteBeacon.fromMap((Map<String, Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(ByteArrayOutputStream stream, Object value)     {
      if (value instanceof EstimoteBeacon) {
        stream.write(128);
        writeValue(stream, ((EstimoteBeacon) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface EstimoteAPI {
    @NonNull EstimoteBeacon fetch(@NonNull String uuid);

    /** The codec used by EstimoteAPI. */
    static MessageCodec<Object> getCodec() {
      return EstimoteAPICodec.INSTANCE;
    }

    /** Sets up an instance of `EstimoteAPI` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, EstimoteAPI api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.EstimoteAPI.fetch", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              String uuidArg = (String)args.get(0);
              if (uuidArg == null) {
                throw new NullPointerException("uuidArg unexpectedly null.");
              }
              EstimoteBeacon output = api.fetch(uuidArg);
              wrapped.put("result", output);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorMap;
  }
}
